libraries:
  Movies:
    metadata_path:
      - repo: /Movies/bestof
      - repo: /Movies/oscars
  TV Shows:
    metadata_path:
      - repo: /TVShows/Networks
  Music:
    metadata_path:
      - repo: /Music/
  Anime:
    metadata_path:
      - repo: /Anime/
playlist_files:
  - repo: /Playlists/Playlists


settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  dimensional_asset_rename: true
  download_url_assets: true
  show_missing_season_assets: true
  show_missing_episode_assets: true
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_missing: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  verify_ssl: true
  custom_repo: https://raw.githubusercontent.com/Pdiddy973/HomeServer/master/PlexMetaManager/
  playlist_sync_to_users: all


webhooks:
  error:
  run_start:
  run_end:
  changes:


plex:
  url: ##################################################################
  token: ##################################################################
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: false


tmdb:
  apikey: ##################################################################
  language: en
  cache_expiration: 60


tautulli:
  url: ##################################################################
  apikey: ##################################################################


radarr:
  url: ##################################################################
  token: ##################################################################
  add_missing: false
  add_existing: false
  root_folder_path: ##################################################################
  monitor: true
  availability: cinemas
  quality_profile: 1080p
  search: true
  tag:
  radarr_path:
  plex_path:


sonarr:
  url: ##################################################################
  token: ##################################################################
  add_missing: false
  add_existing: false
  root_folder_path: ##################################################################
  monitor: all
  quality_profile: HD - 720p/1080p
  language_profile: English
  series_type: standard
  season_folder: true
  search: false
  cutoff_search: false
  tag:
  sonarr_path:
  plex_path:


trakt:
  client_id: ##################################################################
  client_secret: ##################################################################
  authorization:
    access_token: ##################################################################
    token_type: ##################################################################
    expires_in: ##################################################################
    refresh_token: ##################################################################
    scope: ##################################################################
    created_at: ##################################################################
